### ISSUE TITLE
Add functionality to display important dates for an offer, given application_date as a parameter

### ISSUE THREAD

**Issue by m0xb** [CommandAndTriumph/ChurnNBurn#3]
Write a command line program to display important dates for an offer.

**Inputs:** (via command-line argument)
* offer name - the name of the offer to consider
* application date - hypothetical date to submit an application

**Output:** text representing a timeline of the important dates for the offer

**Side effects:** none (no files are created or modified)

Important dates to display:

* Date the offer was issued
* Application date (from the program's input)
* Date by which the user must complete the bonus requirements
* Date on which the user may close the account

Example:

```
$ python important_dates.py "Wells Fargo Cash Wise" 2017-07-25
2017-01-01 * Offer for Wells Fargo Cash Wise credit card issued
           |
           |
2017-07-25 * Application submitted (hypothetical)
           |
           |
2017-10-25 * Deadline to complete offer terms to receive bonus ($200)
           |
           |
2018-01-25 * Credit card may be cancelled
```

Original story description:

> Write a function to display important upcoming + past dates for an offer, given application_date as a parameter

**Comment by WorryingWonton** [comment]
Solved via Important_Dates.py
